# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Jiyu Zhang
tagline:          'A Jekyll theme'
description:      ''
url:              https://jiyuzhang1994.github.io
baseurl:          /

author:
  name:           'Jiyu Zhang'
  url:            https://jiyuzhang1994.github.io

paginate:         10000

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

# plug-ins
