# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Jiyu Zhang
tagline:          ''
description:      'Contact: <br /> jiyu dot zhang at phd dot unibocconi dot it'
url:              'http://hyde.getpoole.com'
baseurl:           

author:
  name:           'Mark Otto'
  url:            'https://twitter.com/mdo'

paginate:         10000

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

# plug-ins
excerpt_separator: '<!--more-->'